server:
  port: 8888


spring:
  profiles:
    active: dev,liv
  application:
    name: config-server    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AymanGhaly/spring-cloud-config-server
          searchPaths: conf*