server:
  port:8080


spring:    
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/AymanGhaly/spring-cloud-config-server
          uri: https://github.com/AymanGhaly/spring-cloud-config-server/tree/master/src/main/resources 
          

management:
  security:
    enabled:false